-- AlterTable
ALTER TABLE "Jam" ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "jammingHours" INTEGER NOT NULL DEFAULT 72,
ADD COLUMN     "suggestionHours" INTEGER NOT NULL DEFAULT 168,
ADD COLUMN     "votingHours" INTEGER NOT NULL DEFAULT 72,
ALTER COLUMN "ratingHours" SET DEFAULT 336,
ALTER COLUMN "slaughterHours" SET DEFAULT 96;
